version: "1"

run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - revive
  disable:
    - dupl
